-- 2022년10월16일 대여 대여중 아니면 대여가능
-- 자동차 ID 기준 내림차순
SELECT CAR_ID,
    MAX(IF ("2022-10-16" BETWEEN START_DATE AND END_DATE,
       "대여중", "대여 가능")) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;