-- 2024/02/16
-- 자동차 종류가 '세단'
-- 10월에 대여를 시작한 기록이 있는 자동차 ID 리스트
-- ID 리스트 중복 X, ID 기준 내림 차순 정렬
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE C.CAR_ID=H.CAR_ID
AND DATE_FORMAT(START_DATE, "%m")="10"
AND CAR_TYPE="세단"
ORDER BY CAR_ID DESC;